# Generated by Django 4.2 on 2024-02-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saver',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
