# Generated by Django 4.2 on 2024-02-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saver', '0002_saver_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saver',
            name='currency',
            field=models.CharField(max_length=3),
        ),
    ]
