# Generated by Django 4.2 on 2024-02-20 13:23

from django.db import migrations, models
import django.db.models.deletion
import ishiro.extra.tools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=ishiro.extra.tools.uuid_generator, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=150)),
                ('amount', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('activity_type', models.CharField(choices=[('income', 'income'), ('expense', 'expense')], max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_category', to='category.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
